parameters:
    locale:                               fr
    locales:                              [fr, en]
    pattern_uuid:                         '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'
    pattern_sha1:                         '[0-9A-Fa-f]{40}'
    pattern_coordinate:                   '-?\d+(\.\d{1,7})?'
    timeline_max_messages:                30
    search_max_results:                   30
    enable_canary:                        "%env(ENABLE_CANARY)%"
    procurations_reply_to_email:          'contact@en-marche.fr'
    transactional_sender_email:           'contact@en-marche.fr'
    transactional_sender_name:            'La République En Marche !'
    campaign_sender_email:                'jemarche@en-marche.fr'
    campaign_sender_name:                 'La République En Marche !'
    feed_ttl:                             60 # in minutes
    legislatives_financial_hotline_email: 'comptes.legislatives@en-marche.fr'
    legislatives_standard_hotline_email:  'campagne.legislatives@en-marche.fr'
    algolia.application_id:               "%env(ALGOLIA_APP_ID)%"
    algolia.api_key:                      "%env(ALGOLIA_BACK_API_KEY)%"
    app_host:                             "%env(APP_HOST)%"
    amp_host:                             "%env(AMP_HOST)%"
    legislatives_host:                    "%env(LEGISLATIVES_HOST)%"
    mooc_base_url:                        "%env(MOOC_BASE_URL)%"
    api_path_prefix:                      "%env(API_PATH_PREFIX)%"
    router.request_context.scheme:        "%env(APP_SCHEME)%"
    router.request_context.host:          "%app_host%"
    image_max_length:                     450px
    webhook.email_subscriptions_secret:   "%env(APP_EMAIL_SUBSCRIPTIONS_WEBHOOK_SECRET)%"
    sonata.exporter.writer.csv.with_bom:  true
    adherent_message_referent_limit: 1000
    adherent_message_committee_limit: 1000
    adherent_message_deputy_limit: 1000
    adherent_message_senator_limit: 1000

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        AppBundle\Adherent\Unregistration\Handlers\UnregistrationAdherentHandlerInterface:
            tags: ['app.adherent.unregistration.handler']

    Algolia\AlgoliaSearchBundle\Indexer\Indexer: '@algolia.indexer'

    AppBundle\Map\StaticMapProviderInterface: '@app.map.google_maps_static_provider'

    AppBundle\Adherent\Handler\RemoveAdherentAndRelatedDataCommandHandler:
        arguments:
            $handlers: !tagged 'app.adherent.unregistration.handler'
        tags: ['messenger.message_handler']

    AppBundle\Adherent\Unregistration\Handlers\:
        resource: ../src/Adherent/Unregistration/Handlers/
